### ISSUE TITLE
[Feat] QuizView의 리팩토링을 진행합니다.

### ISSUE THREAD

**Issue by bluehyudawn** [bluehyudawn/SwiftStudentChallenge2023#1]
### 📝 작업 목적

퀴즈를 풀었을 때 다음 화면으로 이동하는 기존 방식에서, 한 화면에서 모두 변경되는 방향으로 구현합니다.

---

### 🛠️ Tasks

- [x] 퀴즈의 'Stage' Count 세팅
- [x] if문을 활용해서 정답일 경우 stage +=1 적용
- [x] progress 이미지 Array
- [ ] Stage가 최대 퀴즈수를 넘어가지 않도록 구현(앱 종료 방지)
